# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
HIPPO_KEY: AKIAJT5LBD34DLGCK6LA
HIPPO_SECRET: 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
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
