# User
User.create(name: "Hs", email: "hs@hs.com", address: "123 4th St", password: "123", password_confirmation: "123")
User.create(name: "Blake", email: "blake@blake.com", address: "123 4th St", password: "123", password_confirmation: "123")
User.create(name: "Anne", email: "anne@anne.com", address: "123 4th St", password: "123", password_confirmation: "123")
User.create(name: "Whitney", email: "whitney@whitney.com", address: "123 4th St", password: "123", password_confirmation: "123")
User.create(name: "Test", email: "test@test.com", address: "123 4th St", password: "123", password_confirmation: "123")
# Product
Product.create(user_id: 1, name: "blue shirt", photo: "http://bit.ly/19zrTF9", price: 19.99, description: "Pretty and blue", retired: false, inventory: 12)
Product.create(user_id: 1, name: "green shirt", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and green", retired: false, inventory: 12)
Product.create(user_id: 3, name: "red shirt", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and red", retired: false, inventory: 12)
Product.create(user_id: 5, name: "purple shirt", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and purple", retired: false, inventory: 12)
Product.create(user_id: 4, name: "rainbow shirt", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and rainbow", retired: false, inventory: 12)
Product.create(user_id: 2, name: "blue pants", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and blue", retired: false, inventory: 12)
Product.create(user_id: 4, name: "black pants", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and pants", retired: false, inventory: 12)
Product.create(user_id: 1, name: "blue dress", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and blue", retired: false, inventory: 12)
Product.create(user_id: 2, name: "pink dress", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and pink", retired: false, inventory: 12)
Product.create(user_id: 3, name: "black dress", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and black", retired: false, inventory: 12)
Product.create(user_id: 4, name: "red dress", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 19.99, description: "Pretty and red", retired: false, inventory: 12)
Product.create(user_id: 5, name: "red apple", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 0.99, description: "yummy and red", retired: false, inventory: 12)
Product.create(user_id: 2, name: "green apple", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 0.99, description: "yummy and green", retired: false, inventory: 12)
Product.create(user_id: 4, name: "green banana", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 0.99, description: "fresh and green", retired: false, inventory: 12)
Product.create(user_id: 2, name: "yellow banana", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 0.99, description: "yummy and yellow", retired: false, inventory: 12)
Product.create(user_id: 3, name: "french bread", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 0.99, description: "yummy and warm", retired: false, inventory: 12)
Product.create(user_id: 1, name: "chocolate bar", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 0.99, description: "yummy and brown", retired: false, inventory: 12)
Product.create(user_id: 5, name: "whiteboard", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 190.99, description: "new and big", retired: false, inventory: 12)
Product.create(user_id: 4, name: "desk", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 100.99, description: "spacious and good for writing", retired: false, inventory: 12)
Product.create(user_id: 3, name: "chair", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 50.99, description: "Comfy", retired: false, inventory: 12)
Product.create(user_id: 1, name: "podium", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 70.99, description: "good for speeches", retired: false, inventory: 12)
Product.create(user_id: 1, name: "computer", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 1000.99, description: "techy and fast", retired: false, inventory: 12)
Product.create(user_id: 4, name: "blue pen", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 1.99, description: "good at writing in blue", retired: false, inventory: 12)
Product.create(user_id: 4, name: "green pen", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 1.99, description: "good at writing in green", retired: false, inventory: 12)
Product.create(user_id: 4, name: "black pen", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 1.99, description: "good at writing in black", retired: false, inventory: 12)
Product.create(user_id: 2, name: "red pen", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 1.99, description: "good at writing in red", retired: false, inventory: 12)
Product.create(user_id: 5, name: "purple pen", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 1.99, description: "good at writing in purple", retired: false, inventory: 12)
Product.create(user_id: 2, name: "whiteout pen", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 1.99, description: "good at fixing writing in blue", retired: false, inventory: 12)
Product.create(user_id: 4, name: "notebook", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 2.99, description: "good for writing", retired: false, inventory: 12)
Product.create(user_id: 5, name: "dictionary", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 12.99, description: "good for learning", retired: false, inventory: 12)
Product.create(user_id: 1, name:"test", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 12.99, description:"good for practicing", retired: false, inventory: 12)
Product.create(user_id: 5, name: "last year's test", photo: 'http://upload.wikimedia.org/wikipedia/commons/4/48/Hippo_mouth.jpg', price: 12.99, description: "used to be good for learning", retired: true, inventory: 12)

# Category
Category.create(name: "food")
Category.create(name: "fruit")
Category.create(name: "furniture")
Category.create(name: "clothing")
Category.create(name: "women's clothing")
Category.create(name: "shirts")
Category.create(name: "dresses")
Category.create(name: "pens")
Category.create(name: "office supplies")
Category.create(name: "test")

# CategoryProduct
CategoryProduct.create(category_id: 1, product_id: 12)
CategoryProduct.create(category_id: 1, product_id: 13)
CategoryProduct.create(category_id: 1, product_id: 14)
CategoryProduct.create(category_id: 1, product_id: 15)
CategoryProduct.create(category_id: 1, product_id: 16)
CategoryProduct.create(category_id: 1, product_id: 17)
CategoryProduct.create(category_id: 2, product_id: 12)
CategoryProduct.create(category_id: 2, product_id: 13)
CategoryProduct.create(category_id: 2, product_id: 14)
CategoryProduct.create(category_id: 2, product_id: 15)
CategoryProduct.create(category_id: 3, product_id: 19)
CategoryProduct.create(category_id: 3, product_id: 20)
CategoryProduct.create(category_id: 3, product_id: 21)
CategoryProduct.create(category_id: 4, product_id: 1)
CategoryProduct.create(category_id: 4, product_id: 2)
CategoryProduct.create(category_id: 4, product_id: 3)
CategoryProduct.create(category_id: 4, product_id: 4)
CategoryProduct.create(category_id: 4, product_id: 5)
CategoryProduct.create(category_id: 4, product_id: 6)
CategoryProduct.create(category_id: 4, product_id: 7)
CategoryProduct.create(category_id: 4, product_id: 8)
CategoryProduct.create(category_id: 4, product_id: 9)
CategoryProduct.create(category_id: 4, product_id: 10)
CategoryProduct.create(category_id: 4, product_id: 11)
CategoryProduct.create(category_id: 5, product_id: 1)
CategoryProduct.create(category_id: 5, product_id: 8)
CategoryProduct.create(category_id: 5, product_id: 9)
CategoryProduct.create(category_id: 5, product_id: 10)
CategoryProduct.create(category_id: 5, product_id: 11)
CategoryProduct.create(category_id: 6, product_id: 1)
CategoryProduct.create(category_id: 6, product_id: 2)
CategoryProduct.create(category_id: 6, product_id: 3)
CategoryProduct.create(category_id: 6, product_id: 4)
CategoryProduct.create(category_id: 6, product_id: 5)
CategoryProduct.create(category_id: 7, product_id: 8)
CategoryProduct.create(category_id: 7, product_id: 9)
CategoryProduct.create(category_id: 7, product_id: 10)
CategoryProduct.create(category_id: 7, product_id: 11)
CategoryProduct.create(category_id: 8, product_id: 23)
CategoryProduct.create(category_id: 8, product_id: 24)
CategoryProduct.create(category_id: 8, product_id: 25)
CategoryProduct.create(category_id: 8, product_id: 26)
CategoryProduct.create(category_id: 8, product_id: 27)
CategoryProduct.create(category_id: 8, product_id: 28)
CategoryProduct.create(category_id: 9, product_id: 18)
CategoryProduct.create(category_id: 9, product_id: 19)
CategoryProduct.create(category_id: 9, product_id: 20)
CategoryProduct.create(category_id: 9, product_id: 21)
CategoryProduct.create(category_id: 9, product_id: 22)
CategoryProduct.create(category_id: 9, product_id: 23)
CategoryProduct.create(category_id: 9, product_id: 24)
CategoryProduct.create(category_id: 9, product_id: 25)
CategoryProduct.create(category_id: 9, product_id: 26)
CategoryProduct.create(category_id: 9, product_id: 27)
CategoryProduct.create(category_id: 9, product_id: 28)
CategoryProduct.create(category_id: 9, product_id: 29)
CategoryProduct.create(category_id: 9, product_id: 30)
CategoryProduct.create(category_id: 10, product_id: 31)
CategoryProduct.create(category_id: 10, product_id: 32)

# Reviews
# create_table "reviews", force: true do |t|
#     t.integer  "rating"
#     t.integer  "product_id"
#     t.text     "description"
#     t.datetime "created_at"
#     t.datetime "updated_at"
#   end

